export const EVENTS = {
  // Victim
  EMERGENCY_REPORTED: "EMERGENCY_REPORTED",
  EMERGENCY_UPDATED: "EMERGENCY_UPDATED",
  EMERGENCY_ESCALATED: "EMERGENCY_ESCALATED",

  // Rescue
  MISSION_ASSIGNED: "MISSION_ASSIGNED",
  MISSION_ACCEPTED: "MISSION_ACCEPTED",
  MISSION_REJECTED: "MISSION_REJECTED",
  MISSION_DELAYED: "MISSION_DELAYED",
  MISSION_COMPLETED: "MISSION_COMPLETED",

  // Logistics
  VEHICLE_ALLOCATED: "VEHICLE_ALLOCATED",
  VEHICLE_FAILURE: "VEHICLE_FAILURE",
  SAFEZONE_OVERFLOW: "SAFEZONE_OVERFLOW",
};
